### PR TITLE
add dropdown to change image stream

### PR DESCRIPTION
**Pull request by dylanmcreynolds**

### CODE REVIEW

**Comment by dylanmcreynolds** [comment]
One question we had was how to filter based on shape. We thought that at CHX, we'd seen an extra dimension, which we aren't sure how we'd deal with at this point. 

For now, we have the logic:

`if field_shape > 1 and field_shape < 5:`

**Comment by dylanmcreynolds** [comment]
Fixes #3

**Review by birdzix — APPROVED** [review]
@dylanmcreynolds and I worked on this together, I think this is a good step for CatalogViewer being able to be a bit more configurable.

**Comment by birdzix** [comment]
Regarding the question about the logic for filtering image fields, I've created an issue (#4).

**Pull request merged**
